### ISSUE TITLE
Feed the Drygmy

### ISSUE THREAD

**Issue by wsoxfan98** [JRDSandstorm/Kekkle#12]
I'm not sure what he/she/they eats, but he/she/they is not at full health :(

**Comment by codyberg37** [comment]
A crew to brew healing potions has been dispatched

**Comment by codyberg37** [comment]
Melons not found, dispatching a team to locate

**Comment by codyberg37** [comment]
Potions administered, drygmy is healthy and has been temporarily been relocated to the basement to ensure no further danger comes to it
