### ISSUE TITLE
Automated ore processing

### ISSUE THREAD

**Issue by stermini** [JRDSandstorm/Kekkle#8]
I have all these great resources that I've obtained but nothing to do with them! Perhaps a chest to automatically convert ore into 2 TIMES (!!!) as many ingots would be greatly helpful to the team!

**Comment by wsoxfan98** [comment]
Great idea stermini! I will forward this to the rest of the team and see what we can do :)

**Comment by wsoxfan98** [comment]
Encountered a problem with Refinedpipes and Silents Mechanisms. Working on a fix. ETA 10.

**Comment by wsoxfan98** [comment]
Issue has been solved. 
_Under budget and ahead of schedule._

**Comment by JRDSandstorm** [comment]
Good job wsoxfan98!  Here at Kekkle we always appreciate employees who go above and beyond to resolve issues with positive SPI and CPI scores!  Keep up the good work!
