### ISSUE TITLE
Food Production

### ISSUE THREAD

**Issue by codyberg37** [JRDSandstorm/Kekkle#9]
In order to support blood magic progression, a consistent and reliable source of food is desperately required in order to have adequate health regeneration. All hands on deck requested.

**Comment by wsoxfan98** [comment]
Deferring issue to Electrical and Construction.

**Comment by JRDSandstorm** [comment]
Issue description contains keyword "magic".  Deferring issue to Magic.

**Comment by codyberg37** [comment]
4 Hopper botany pots growing wheat installed, currently makes 1.333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333 bread every 48 seconds. Testing to observe if this is enough production
